contextSource: env
ossBucketName: xiliu-vscode
vscode:
  host: 127.0.0.1
  port: 8080
  dataDirectory: /Users/congxiao/go/src/start-serverless-webide-web/src/target/vscode-server
  binaryDirectory: /Users/congxiao/go/src/start-serverless-webide-web/src/third_party/openvscode-server-v1.67.0-darwin-amd64/bin
  dataOssPath: tests/vscode-server/vscode-server-data.tar.gz
workspace:
  directory: /Users/congxiao/go/src/start-serverless-webide-web/src/target/workspace
  ossPath: tests/vscode-server/workspace.tar.gz
